'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18034
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources

    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
    Friend Class CommandLineTools

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
        Friend Sub New()
            MyBase.New()
        End Sub

        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CommandLineTools", GetType(CommandLineTools).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        '''<summary>
        '''  Looks up a localized string similar to This will print help.
        '''</summary>
        Friend Shared ReadOnly Property S_DEFAULT_HELP_DESC() As String
            Get
                Return ResourceManager.GetString("S_DEFAULT_HELP_DESC", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to help.
        '''</summary>
        Friend Shared ReadOnly Property S_DEFAULT_HELP_LONG() As String
            Get
                Return ResourceManager.GetString("S_DEFAULT_HELP_LONG", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to h.
        '''</summary>
        Friend Shared ReadOnly Property S_DEFAULT_HELP_SHORT() As String
            Get
                Return ResourceManager.GetString("S_DEFAULT_HELP_SHORT", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to This will omit ouput except errors.
        '''</summary>
        Friend Shared ReadOnly Property S_DEFAULT_VERBOSE_DESC() As String
            Get
                Return ResourceManager.GetString("S_DEFAULT_VERBOSE_DESC", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to quiet.
        '''</summary>
        Friend Shared ReadOnly Property S_DEFAULT_VERBOSE_LONG() As String
            Get
                Return ResourceManager.GetString("S_DEFAULT_VERBOSE_LONG", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to q.
        '''</summary>
        Friend Shared ReadOnly Property S_DEFAULT_VERBOSE_SHORT() As String
            Get
                Return ResourceManager.GetString("S_DEFAULT_VERBOSE_SHORT", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to --{0} (-{1}) is required.
        '''</summary>
        Friend Shared ReadOnly Property S_ERR_ARG_REQUIRED() As String
            Get
                Return ResourceManager.GetString("S_ERR_ARG_REQUIRED", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to This command does not ask for main arguments.
        '''</summary>
        Friend Shared ReadOnly Property S_ERR_ARGS_WHEN_NOARGS() As String
            Get
                Return ResourceManager.GetString("S_ERR_ARGS_WHEN_NOARGS", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Empty short option (as in - ). To separate main arguments use --..
        '''</summary>
        Friend Shared ReadOnly Property S_ERR_EMPTY_SHORT_OPTION() As String
            Get
                Return ResourceManager.GetString("S_ERR_EMPTY_SHORT_OPTION", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to &quot;Long&quot; short option (as in -myopt ).
        '''</summary>
        Friend Shared ReadOnly Property S_ERR_LONG_SHORT_OPTION() As String
            Get
                Return ResourceManager.GetString("S_ERR_LONG_SHORT_OPTION", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to This command requires main arguments.
        '''</summary>
        Friend Shared ReadOnly Property S_ERR_NOARGS_WHEN_REQUIRED() As String
            Get
                Return ResourceManager.GetString("S_ERR_NOARGS_WHEN_REQUIRED", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Non-optional argument ({0}) not admitted when the last one ({1}) is already optional.
        '''</summary>
        Friend Shared ReadOnly Property S_ERR_NON_OPTIONAL_AFTER_OPTIONAL() As String
            Get
                Return ResourceManager.GetString("S_ERR_NON_OPTIONAL_AFTER_OPTIONAL", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Not enough subarguments given for option --{0}.
        '''</summary>
        Friend Shared ReadOnly Property S_ERR_NOT_ENOUGH_SUBARGS() As String
            Get
                Return ResourceManager.GetString("S_ERR_NOT_ENOUGH_SUBARGS", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to This option doesn&apos;t exist.
        '''</summary>
        Friend Shared ReadOnly Property S_ERR_OPTION_NOT_EXIST() As String
            Get
                Return ResourceManager.GetString("S_ERR_OPTION_NOT_EXIST", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to You must provide names for all the required unnamed arguments.
        '''</summary>
        Friend Shared ReadOnly Property S_ERR_REQUIRED_MAIN_ARGUMENTS_WITHOUT_NAME() As String
            Get
                Return ResourceManager.GetString("S_ERR_REQUIRED_MAIN_ARGUMENTS_WITHOUT_NAME", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to &quot;Short&quot; long option (as in --o ).
        '''</summary>
        Friend Shared ReadOnly Property S_ERR_SHORT_LONG_OPTION() As String
            Get
                Return ResourceManager.GetString("S_ERR_SHORT_LONG_OPTION", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Short parameter name ({0}) must be shorter than long parameter name ({1}).
        '''</summary>
        Friend Shared ReadOnly Property S_ERR_SHORT_LONGER_THAN_LONG() As String
            Get
                Return ResourceManager.GetString("S_ERR_SHORT_LONGER_THAN_LONG", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to No subarguments admitted when the last one is of type List.
        '''</summary>
        Friend Shared ReadOnly Property S_ERR_SUBARG_AFTER_LIST() As String
            Get
                Return ResourceManager.GetString("S_ERR_SUBARG_AFTER_LIST", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Too many subarguments given for option --{0}.
        '''</summary>
        Friend Shared ReadOnly Property S_ERR_TOO_MANY_SUBARGS() As String
            Get
                Return ResourceManager.GetString("S_ERR_TOO_MANY_SUBARGS", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Empty subargument.
        '''</summary>
        Friend Shared ReadOnly Property S_ERR_VOID_SUBARGUMENT() As String
            Get
                Return ResourceManager.GetString("S_ERR_VOID_SUBARGUMENT", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to REQUIRED. .
        '''</summary>
        Friend Shared ReadOnly Property S_HELP_REQUIRED() As String
            Get
                Return ResourceManager.GetString("S_HELP_REQUIRED", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Usage.
        '''</summary>
        Friend Shared ReadOnly Property S_HELP_USAGE() As String
            Get
                Return ResourceManager.GetString("S_HELP_USAGE", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Options.
        '''</summary>
        Friend Shared ReadOnly Property S_OPTIONS() As String
            Get
                Return ResourceManager.GetString("S_OPTIONS", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Subarguments must be separated by spaces..
        '''</summary>
        Friend Shared ReadOnly Property S_SUBARGUMENTS_SEPARATED() As String
            Get
                Return ResourceManager.GetString("S_SUBARGUMENTS_SEPARATED", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
